# Generated by Django 3.2.9 on 2021-11-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dr',
            fields=[
                ('drid', models.IntegerField(db_column='DrID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hosp',
            fields=[
                ('hospid', models.IntegerField(db_column='HospID', primary_key=True, serialize=False)),
                ('hopsname', models.CharField(db_column='HopsName', max_length=45)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=45, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=45, null=True)),
                ('hospnumber', models.CharField(blank=True, db_column='HospNumber', max_length=11, null=True)),
                ('zipcode', models.CharField(blank=True, db_column='ZipCode', max_length=11, null=True)),
            ],
            options={
                'db_table': 'hosp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientid', models.IntegerField(db_column='PatientID', primary_key=True, serialize=False)),
                ('height', models.FloatField(blank=True, db_column='Height', null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('emergencycontact', models.CharField(blank=True, db_column='emergencyContact', max_length=11, null=True)),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('prsnid', models.CharField(db_column='PrsnID', max_length=11, primary_key=True, serialize=False)),
                ('prsnname', models.CharField(db_column='PrsnName', max_length=45)),
                ('lastname', models.CharField(db_column='Lastname', max_length=45)),
                ('prsnphone', models.CharField(db_column='PrsnPhone', max_length=11)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=45, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=45, null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=6, null=True)),
                ('birth', models.IntegerField(blank=True, db_column='Birth', null=True)),
            ],
            options={
                'db_table': 'person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('pharid', models.IntegerField(db_column='PharID', primary_key=True, serialize=False)),
                ('pharname', models.CharField(db_column='PharName', max_length=45)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=45, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=45, null=True)),
                ('pharphone', models.CharField(blank=True, db_column='PharPhone', max_length=11, null=True)),
                ('zipcode', models.CharField(blank=True, db_column='ZipCode', max_length=11, null=True)),
            ],
            options={
                'db_table': 'pharmacy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proficiency',
            fields=[
                ('proid', models.IntegerField(db_column='ProID', primary_key=True, serialize=False)),
                ('proname', models.CharField(db_column='ProName', max_length=45)),
            ],
            options={
                'db_table': 'proficiency',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uni',
            fields=[
                ('uniid', models.IntegerField(db_column='UniID', primary_key=True, serialize=False)),
                ('uniname', models.CharField(db_column='UniName', max_length=45)),
            ],
            options={
                'db_table': 'uni',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('visitid', models.IntegerField(db_column='VisitID', primary_key=True, serialize=False)),
                ('visitdate', models.DateField(db_column='VisitDate')),
                ('appointmentdate', models.DateField(db_column='AppointmentDate')),
                ('status', models.CharField(db_column='Status', max_length=15)),
            ],
            options={
                'db_table': 'visit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('workid', models.IntegerField(db_column='WorkID', primary_key=True, serialize=False)),
                ('hospid', models.IntegerField(blank=True, db_column='HospID', null=True)),
                ('fee', models.IntegerField(blank=True, db_column='Fee', null=True)),
                ('start', models.TimeField(blank=True, db_column='Start', null=True)),
                ('end', models.TimeField(blank=True, db_column='End', null=True)),
                ('weekday', models.CharField(blank=True, db_column='Weekday', max_length=10, null=True)),
            ],
            options={
                'db_table': 'work',
                'managed': False,
            },
        ),
    ]
